### ISSUE TITLE
Possible to use script vlan_elrp_check for enabling ELRP on all VLANs, instead of running one-time?

### ISSUE THREAD

**Issue by wh0else** [extremenetworks/ExtremeScripting#73]
The script vlan_elrp_check runs ELRP on all VLANs one-time only, but how can it be used to enable ELRP on all VLANs permanently?

**Comment by rbrt-weiler** [comment]
As a hotfix you could just comment out line 120 in the script. This will keep ELRP active no matter what. Diff:

```
120c120
<         (exsh.clicmd('disable elrp', True))
---
>         # (exsh.clicmd('disable elrp', True))
```

However, I do not think that this is what you want, as the ELRP config in the script is designed as a one-shot type (line 103). I guess you want some type of periodic check, right?

**Comment by stewilliams-extr** [comment]
Is there something that is missing in the ELRP feature.  This script was made to help see what vlan might have a loop.

**Comment by bparkerextr** [comment]
> Is there something that is missing in the ELRP feature. This script was made to help see what vlan might have a loop.

The "configure elrp" command forces you to enter each VLAN one-by-one. We can't "configure elrp periodic vlan 1-10 ...." or anything like t hat.

**Comment by wh0else** [comment]
> > Is there something that is missing in the ELRP feature. This script was made to help see what vlan might have a loop.
> 
> The "configure elrp" command forces you to enter each VLAN one-by-one. We can't "configure elrp periodic vlan 1-10 ...." or anything like that.

+1

**Comment by stewilliams-extr** [comment]
All you need to do to make the script configure ELRP is the change/remove the below lines:

- Change line 103 to the correct command
- remove lines 111-121

@wh0else I've submitted the request to enable elrp periodic on all vlans or 1-10 as you stated.

**Comment by stewilliams-extr** [comment]
@PrivacyNemesis,

I have updated the script to work with newer software 32.1+.

https://github.com/extremenetworks/ExtremeScripting/commit/454e651b54c51f6050ec5708334e4253e39b065c

**Comment by PrivacyNemesis** [comment]
Dear @stewilliams-extr ,

I would like to extend my gratitude for your prompt action in providing the updated code for the ELRP configuration check script. Your assistance is greatly appreciated, and I am pleased to see that we now have a more relevant script to ensure network security and stability.

In the process of implementing the updated code, I noticed an important observation regarding the firmware versions of some switches. It appears that certain switches are still running firmware versions 15, 16, or 30 and XIQ-SE is python 2.7. As a result, the current update is incompatible with these firmware versions, causing potential issues during the update process.

I wanted to bring this to your attention so that we can assess the situation and determine the best course of action moving forward. It may be necessary to consider alternative approaches or modifications to the code to ensure compatibility with the older firmware versions.

Your guidance and expertise in addressing this matter would be invaluable. I look forward to discussing possible solutions and working together to overcome this challenge.

**Comment by stewilliams-extr** [comment]
It will work on Python 2 and Python 3 now.  

https://github.com/extremenetworks/ExtremeScripting/commit/40f68c789b0b79f4857099a7a40eb0773e12e83b

**Comment by PrivacyNemesis** [comment]
@stewilliams-extr I still have this error that appears, no matter which EXOS switch is in versions 16, 22, 30, 32. The script stops as soon as the exsh module is imported. I don’t know what to do anymore.

--

XIQ-SE User Domain: 
IP: 10.255.0.2
Traceback (most recent call last):
  File "<string>", line 7, in <module>
ImportError: No module named exsh
